CLIENT_ID = "388d872b-594c-8189-8588-003733172ccf"
CLIENT_SECRET = "secret_vHsMNxIbFGuWoTnxzboufUYGo9bK8ofe7pUY1X61z2I"
# Dentro do painel de Secrets do Streamlit
[notion_tokens]
luiz = "secret_notion_token_do_luiz..."
guilherme = "secret_notion_token_do_guilherme..."
diego = "secret_notion_token_do_diego..."
daniel = "secret_notion_token_do_daniel..."
yan = "secret_notion_token_do_yan..."
gustavo = "secret_notion_token_do_gustavo..."
marina = "secret_notion_token_da_marina..."
jonas = "secret_notion_token_do_jonas..."
arthurs = "secret_notion_token_do_arthurs..."
